version: "3.8"
services:
  web:
    build: .
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    ports: 
      - 8002:5000
    env_file: 
      - database.env
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    env_file: 
      - database.env
    ports:
      - 8001:5432
    volumes: 
      - mycustomerdata:/var/lib/postgresql/data 

volumes:
  mycustomerdata: